### ISSUE TITLE
Contact pour firmware shelly dimmer

### ISSUE THREAD

**Issue by PlaneteDomo** [Mollayo/Shelly-Dimmer-2#3]
Bonjour Mollayo,
Comment pouvons nous nous contacter ? 
Merci d'avance

**Comment by Mollayo** [comment]
D'accord. Quelle est votre adresse email ?

**Comment by PlaneteDomo** [comment]
contact@planete-domotique.com

**Comment by PlaneteDomo** [comment]
Bonjour,
Avez vous envoyé votre email du coup ?
Je n'ai rien reçu
Cordialement

**Comment by Mollayo** [comment]
Voilà mon email : fredcord@gmail.com.
